---
# disable_cloud-init_services/tasks/main.yml

- name: 'Disable and stop all cloud-init services'
  service:
    name: "{{ item }}"
    state: 'stopped'
    enabled: 'false'
  with_items: "{{ cloud_init_services }}"
  when: 'not (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")'

- name: 'Generate /etc/cloud/cloud-init.disabled'
  copy:
    dest: '/etc/cloud/cloud-init.disabled'
    content: 'disabled by ansible\n'
    owner: 'root'
    group: 'root'
    mode: '0644'
